/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

#include "nsISupports.idl"
#include "nsIScriptableInputStream.idl"

/**
 * Interface for a wrapper of a JS WebVTTParser (vtt.js).
 */
[scriptable, uuid(1604a67f-3b72-4027-bcba-6dddd5be6b10)]
interface nsIWebVTTParser : nsISupports
{
  /**
   * Attempts to parse the stream's data as WebVTT format.
   *
   * @param data The data stream that contains the WebVTT data received by the
   *             Necko consumer so far.
   */
  void parse(in string data);

  /**
   * Flush indicates that no more data is expected from the stream. As such the
   * parser should try to parse any kind of partial data it has.
   */
  void flush();
};
